# Generated by Django 5.1.4 on 2024-12-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetingmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmembership',
            name='status',
            field=models.CharField(choices=[('no data', 'Нет данных'), ('pending', 'Подтверждено, но не активно'), ('active', 'Активно'), ('closed', 'Закрыто')], default='no data', max_length=128),
        ),
        migrations.AlterField(
            model_name='meetingmembership',
            name='joined_at',
            field=models.DateTimeField(),
        ),
    ]
