# Generated by Django 5.1.4 on 2024-12-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingmembership_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingmembership',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
